export default [
  {
    id: 'camera',
    title: 'Views',
    type: 'radio',
    data: {
      1: 'Default',
      2: 'Near',
      3: 'Orthographic',
      4: 'Map',
      5: 'CameraView',
      6: 'Overhead'
    },
    supportInOfflineView: true,
  },
  {
    id: 'perception',
    title: 'Perception',
    type: 'checkbox',
    data: {
      perceptionPointCloud: 'Point Cloud',
      // perceptionObjectTopic: 'Object Topic',
      perceptionBicycle: 'Bicycle',
      perceptionCipv: 'Closest In-Path Vehicle',
      perceptionPedestrian: 'Pedestrian',
      perceptionVehicle: 'Vehicle',
      perceptionHeading: 'Heading',
      perceptionId: 'Id',
      perceptionObstacleInfo: 'Speed',
      perceptionVelocity: 'Velocity',
      showPolygon:'showPolygon',
      showObstacleBarrier: 'Barrier',
      perceptionUnknown: 'Unknown',
      perceptionUnknownMovable: 'Unknown Movable',
      perceptionUnknownUnmovable: 'Unknown Stationary',
      // perceptionTypeStaticUnkonwn: 'TYPE_STATIC_UNKNOWN',
      // perceptionLaneMarker: 'Lane Marker',
      // perceptionLidarSensor: 'Lidar Sensor',
      // perceptionRadarSensor: 'Radar Sensor',
      // perceptionCameraSensor: 'Camera Sensor',
      // perceptionV2xInfo:'V2X',
    },
    supportInOfflineView: true,
  },
  {
    id: 'perception_topic',
    title: 'Object Topic',
    type: 'checkbox',
    data: {
      showObstaclesPostFusionObject: '/post_fusion_object',
      showObstaclesBevObject: '/bev_object',
      showObstaclesPvFmNarrowObject: '/pv_fm_narrow_object',
      showObstaclesPvFmWideObject: '/pv_fm_wide_object',
      showObstaclesPvLbPinholeObject: '/pv_lb_pinhole_object',
      showObstaclesPvRbPinholeObject: '/pv_rb_pinhole_object',
      showObstaclesPvRfPinholeObject: '/pv_rf_pinhole_object',
      showObstaclesPvLfPinholeObject: '/pv_lf_pinhole_object',
      showObstaclesPvFmFisheyeObject: '/pv_fm_fisheye_object',
      showObstaclesPvLmFisheyeObject: '/pv_lm_fisheye_object',
      showObstaclesPvRmFisheyeObject: '/pv_rm_fisheye_object',
      showObstaclesPvBmFisheyeObject: '/pv_bm_fisheye_object',
      showObstaclesBevPostObject: '/bev_post_object',
      showObstaclesPvPostFmNarrowObject: '/pv_post_fm_narrow_object',
      showObstaclesPvPostFmWideObject: '/pv_post_fm_wide_object',
      showObstaclesPvPostLbPinholeObject: '/pv_post_lb_pinhole_object',
      showObstaclesPvPostRbPinholeObject: '/pv_post_rb_pinhole_object',
      showObstaclesPvPostRfPinholeObject: '/pv_post_rf_pinhole_object',
      showObstaclesPvPostLfPinholeObject: '/pv_post_lf_pinhole_object',
      showObstaclesOccupancyObject: '/occupancy_object',
    },
    supportInOfflineView: true,
  },
  {
    id: 'prediction',
    title: 'Prediction',
    type: 'checkbox',
    data: {
      showPredictionMonitor: 'Prediction Monitor',
      showEfficientLaneMonitor: 'Efficient Lane Monitor',
      efficientLane: 'Efficient Lane',
      nnPath: 'NN Path high Prob',
      nnPathLow: 'NN Path Low Prob',
      globalAction: 'NN Path Action',
      efficientNavi: 'Efficient Navi',
      showTurnType: 'Turn Type',
      showLowProb: 'Low Probability',
      showLowProbColor: 'Low Probability Color',
      showPncDebug: 'LcNN Debug',
      predictionMajor: 'Major Prediction Line',
      predictionMinor: 'Minor Prediction Line',
      showEllipse: 'Traj Uncertainty',
      showPredictionPath: 'Prediction Path',
      decisionMain: 'Main Decision',
      decisionObstacle: 'Obstacle Decision',
      predictionDecision: 'Prediction Decision',
      curbTag: 'Prediction Curb',
      roadStructureCurb: 'Road Structure Curb',
      vehicleFlowLines: 'Vehicle Flow',
      goalLaneInJunction: 'Goal Lane In Junction',
      obstacleStatus: 'Obstacle Status',
      predictionInteractiveTag: 'Interactive Tag',
      predictionGaussianInfo: 'Gaussian Info',
      predictionPriority: 'Priority',
    },
    supportInOfflineView: true,
  },
  // {
  //   id: 'routing',
  //   title: 'Routing',
  //   type: 'checkbox',
  //   data: {
  //     routing: 'Routing Line',
  //   },
  //   supportInOfflineView: true,
  // },
  // {
  //   id: 'decision',
  //   title: 'Decision',
  //   type: 'checkbox',
  //   data: {
  //     decisionMain: 'Main Decision',
  //     decisionObstacle: 'Obstacle Decision',
  //   },
  //   supportInOfflineView: true,
  // },
  {
    id: 'planning',
    title: 'Planning',
    type: 'checkbox',
    data: {
      showPNCMonitor: 'PNC Monitor',
      showPncNnCanvas: 'Pnc Nn Canvas',
      egoPathPoint: 'Ego Path Point',
      showLonBehavior: 'Lon Behavior',
      multiPolicy: 'Multi Policy',
      showDimensionalCar: 'Dimensional Car',
      planningCar: 'Planning Car',
      showTopoTree: 'Topo Tree',
      showRwText: 'Rw Text',
      planningPath: 'Planning All Path',
      planningEgoPath: 'Path',
      planningTrajectory: 'Planning Trajectory',
      // rssInfo: 'RSS Info',
    },
    supportInOfflineView: true,
  },
  // {
  //   id: 'position',
  //   title: 'Position',
  //   type: 'checkbox',
  //   data: {
  //     positionLocalization: 'Localization',
  //     positionCloseLoop: 'Virtual Localization',
  //     virtualChassis: 'Virtual Chassis',
  //     positionGps: 'GPS',
  //     positionShadow: 'Shadow',
  //   },
  //   supportInOfflineView: true,
  // },
  // {
  //   id: 'map',
  //   title: 'Map',
  //   type: 'checkbox',
  //   data: {
  //     mapCrosswalk: 'Crosswalk',
  //     mapClearArea: 'Clear Area',
  //     mapJunction: 'Junction',
  //     mapPncJunction: 'PNC Junction',
  //     mapLane: 'Lane',
  //     mapCenterLane: 'Center Lane',
  //     mapRoad: 'Road',
  //     mapSignal: 'Signal',
  //     mapStopSign: 'Stop Sign',
  //     mapYield: 'Yield Sign',
  //     mapSpeedBump: 'Speed Bump',
  //     mapParkingSpace: 'Parking Space',
  //     mapLaneId: 'Lane Id',
  //   },
  //   supportInOfflineView: false,
  // },
];