# A map from path names defined planning_internal.proto
# to display ones on Dreamview graphs.
# This display names are used in the graph settings
# such as speed graph as well.
nameMapper:
    planning_reference_line_0: ReferenceLine
    DpStSpeedOptimizer: SpeedHeuristic
    PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER: PlannedSpeed

# Planning Graph settings
slGraph:
    title: 'QP Path - sl graph'
    options:
        legend:
            display: false
        axes:
            x:
                min: 0
                max: 200
                labelString: 's - ref_line (m)'
            y:
                min: -5
                max: 5
                labelString: 'l (m)'
    properties:
        lines:
            aggregatedBoundaryLow:
                color: 'rgba(48, 165, 255, 1)' # blue
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
            aggregatedBoundaryHigh:
                color: 'rgba(48, 165, 255, 1)' # blue
                borderWidth: 2
                pointRadius: 0
                lineTension: 0
                fill: false
                showLine: true
            pathLine:
                color: 'rgba(225, 225, 225, 0.7)' # white
                borderWidth: 2
                pointRadius: 0.5
                fill: false
                showLine: false
            mapLowerBound:
                color: 'rgba(54, 162, 235, 0.4)' # blue
                borderWidth: 2
                pointRadius: 0
                fill: 'start'
                showLine: true
            mapUpperBound:
                color: 'rgba(54, 162, 235, 0.4)' # blue
                borderWidth: 2
                pointRadius: 0
                fill: 'end'
                showLine: true
            staticObstacleLowerBound:
                color: 'rgba(255, 0, 0, 0.8)' # red
                borderWidth: 2
                pointRadius: 0
                fill: 'start'
                showLine: true
            staticObstacleUpperBound:
                color: 'rgba(255, 0, 0, 0.8)' # red
                borderWidth: 2
                pointRadius: 0
                fill: 'end'
                showLine: true
            dynamicObstacleLowerBound:
                color: 'rgba(255, 206, 86, 0.2)' # yellow
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
            dynamicObstacleUpperBound:
                color: 'rgba(255, 206, 86, 0.2)' # yellow
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
stGraph:
    options:
        legend:
            display: false
        axes:
            x:
                min: -2
                max: 10
                labelString: 't (second)'
            y:
                min: -10
                max: 220
                labelString: 's (m)'
    properties:
        lines:
            curveLine:
                color: 'rgba(225, 225, 0, 0.5)' # yellow
                borderWidth: 2
                pointRadius: 1
                fill: false
                showLine: false
            speedProfileLine:
                color: 'rgba(225, 0, 0, 1)' # red
                borderWidth: 2
                pointRadius: 1
                fill: false
                showLine: false
            kernelCruise:
                color: 'rgba(27, 249, 105, 0.5)' # green
                borderWidth: 2
                pointRadius: 1
                fill: false
                showLine: false
            kernelFollow:
                color: 'rgba(255, 206, 86, 0.5)' # yellow
                borderWidth: 2
                pointRadius: 1
                fill: false
                showLine: false
            vtProfilePoint:
                color: 'rgba(255, 255, 255, 0.8)' # white
                borderWidth: 2
                pointRadius: 1
                fill: false
                showLine: false
    datasets:
        - name: SPEED_HEURISTIC_OPTIMIZER
          graphTitle: Speed Heuristic
          isShow: showSpeedHeuristic
        - name: ILQR_SPEED_OPTIMIZER
          graphTitle: Planning S-T Graph
          isShow: showPlanningSTGraph
speedLimitRef:
    options:
        legend:
            display: true
        axes:
            x:
                labelString: 's (m)'
            y:
                min: 0
                max: 12
                labelString: 'Tag'
    properties:
        lines:
            basicTag:
                color: 'rgba(225, 225, 0, 0.5)' # yellow
                borderWidth: 2
                pointRadius: 1
                fill: false
                showLine: false
            bonusTag:
                color: 'rgba(255, 255, 255, 0.8)' # white
                borderWidth: 2
                pointRadius: 1
                fill: false
                showLine: false
    datasets:
        - name: ILQR_SPEED_OPTIMIZER
          graphTitle: Speed Limit Reference
          isShow: true
stSpeedGraph:
    options:
        legend:
            display: true
        axes:
            x:
                min: -10
                max: 220
                labelString: 's - qp_path(m)'
            y:
                min: -1
                max: 40
                labelString: 'v (m/s)'
    properties:
        lines:
            upperConstraint:
                color: 'rgba(54, 162, 235, 1)' # blue
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
            lowerConstraint:
                color: 'rgba(54, 162, 235, 1)' # blue
                borderWidth: 4
                pointRadius: 0
                fill: false
                showLine: true
            planned:
                color: 'rgba(225, 225, 225, 0.5)' # white
                borderWidth: 4
                pointRadius: 0
                fill: false
                showLine: true
            limit:
                color: 'rgba(255, 0, 0, 0.5)' # red
                borderWidth: 4
                pointRadius: 0
                fill: false
                showLine: true
    datasets:
        - name: PIECEWISE_JERK_NONLINEAR_SPEED_OPTIMIZER
          graphTitle: Planning V-T Graph
          isShow: showPlanningVTGraph
speedGraph:
    isShow: showPlanningSpeed
    title: 'Planning Speed'
    options:
        legend:
            display: true
        axes:
            x:
                min: -2
                max: 10
                labelString: 't (second)'
            y:
                min: -1
                max: 40
                labelString: 'speed (m/s)'
    properties:
        lines:
            VehicleSpeed:
                color: 'rgba(255, 0, 0, 0.8)' # red
                borderWidth: 1
                pointRadius: 1
                fill: false
                showLine: false
            SpeedHeuristic:
                color: 'rgba(27, 249, 105, 0.5)' # green
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
            PlannedSpeed:
                color: 'rgba(54, 162, 235, 1)' # blue
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
accelerationGraph:
    isShow: showPlanningAcceleration
    title: 'Planning Acceleration'
    options:
        legend:
            display: false
        axes:
            x:
                min: -2
                max: 10
                labelString: 't (second)'
            y:
                min: -4.0
                max: 3.5
                labelString: 'acceleration (m/s^2)'
    properties:
        lines:
            acceleration:
                color: 'rgba(255, 0, 0, 0.8)' # red
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
planningKappaGraph:
    isShow: showPlanningKappa
    title: 'Planning Kappa'
    options:
        legend:
            display: true
        axes:
            x:
                labelString: 't (sec)'
            y:
                labelString: 'kappa'
    properties:
        lines:
            Trajectory:
                color: 'rgba(1, 209, 193, 0.8)' # Turkish green
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
referenceLineKappaGraph:
    isShow: showReferenceLineKappa
    title: 'Reference Line Kappa'
    options:
        legend:
            display: true
        axes:
            x:
                labelString: 's (m)'
            y:
                labelString: 'kappa'
    properties:
        lines:
            ReferenceLine:
                color: 'rgba(255, 0, 0, 0.8)' # red
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
planningDkappaGraph:
    isShow: showPlanningKappaDerivative
    title: 'Planning Kappa Derivative'
    options:
        legend:
            display: true
        axes:
            x:
                labelString: 't (sec)'
            y:
                labelString: 'dkappa'
    properties:
        lines:
            Trajectory:
                color: 'rgba(1, 209, 193, 0.8)' # Turkish green
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
referenceLineDkappaGraph:
    isShow: showReferenceLineKappaDerivative
    title: 'Reference Line Kappa Derivative'
    options:
        legend:
            display: true
        axes:
            x:
                labelString: 's (m)'
            y:
                min: -0.02
                max: 0.02
                labelString: 'dkappa'
    properties:
        lines:
            ReferenceLine:
                color: 'rgba(255, 0, 0, 0.8)' # red
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
            PlannedSpeed:
                color: 'rgba(54, 162, 235, 1)' # blue
                borderWidth: 5
                pointRadius: 0
                fill: false
                showLine: true
planningThetaGraph:
    isShow: showPlanningTheta
    title: 'Planning Theta'
    options:
        legend:
            display: true
        axes:
            x:
                labelString: 't (sec)'
            y:
                labelString: 'theta'
    properties:
        lines:
            Trajectory:
                color: 'rgba(1, 209, 193, 0.8)' # Turkish green
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
referenceLineThetaGraph:
    isShow: showReferenceLineTheta
    title: 'Reference Line Theta'
    options:
        legend:
            display: true
        axes:
            x:
                labelString: 's (m)'
            y:
                labelString: 'theta'
    properties:
        lines:
            ReferenceLine:
                color: 'rgba(255, 0, 0, 0.8)' # red
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
nnpathVt:
    isShow: showNnpathVtSpeed
    title: ''
    options:
        aspectRatio: 0.9
        legend:
            display: true
        axes:
            x:
                min: 0
                max: 5
                labelString: 't (second)'
            y:
                min: -1
                max: 30
                labelString: 'speed (m/s)'
    properties:
        lines:
            NnpathSpeed:
                color: 'rgba(54, 162, 235, 1)'
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
            NnpathSpeedAdd:
                color: 'rgba(244, 198, 176, 1)'
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
            NnpathSpeedSub:
                color: 'rgba(244, 198, 176, 1)'
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
            VehicleSpeed:
                color: 'rgba(255, 0, 0, 0.8)'
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
debugStGraph:
    options:
        legend:
            display: true
        axes:
            x:
                labelString: 't (sec)'
                min: 0
                max: 8
            y:
                min: -1
                labelString: 'v (m/s)'
    properties:
        lines:
            vtSpeedProfile:
                color: 'rgba(1, 209, 193, 0.8)'
                borderWidth: 3
                pointRadius: 0
                fill: false
                showLine: true
            speedProfile:
                color: 'rgba(54, 162, 235, 1)'
                borderWidth: 3
                pointRadius: 0
                fill: false
                showLine: true
            speedReference:
                color: 'rgba(255, 0, 0, 0.5)'
                borderWidth: 3
                pointRadius: 0
                fill: false
                showLine: true
    datasets:
        - name: ILQR_SPEED_OPTIMIZER
          graphTitle: Planning V-T Graph
          isShow: showPlanningVTGraph
