speedGraph:
    options:
        hideTitle: true
        legend:
            display: false
        axes:
            x:
                labelString: ''
                hidden: false
                maxTicksLimit: 20
                stepSize: 4
            y:
                min: 0.0
                max: 30.0
                stepSize: 5
                labelString: ''
    properties:
        lines:
            real:
                # color: 'rgba(0, 106, 255, 1)' # blue
                color: 'rgba(0, 255, 0, 1)' # blue
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: ture
            now:
                color: 'rgba(219, 26, 244, 1)'
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
accelerationGraph:
    options:
        hideTitle: true
        legend:
            display: false
        axes:
            x:
                labelString: ''
                hidden: false
                maxTicksLimit: 20
                stepSize: 4
            y:
                min: -6.0
                max: 6.0
                stepSize: 1
                labelString: ''
    properties:
        lines:
            real:
                # color: 'rgba(0, 106, 255, 1)' # blue
                color: 'rgba(255, 0, 0, 1)' # red
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: ture
            now:
                color: 'rgba(219, 26, 244, 1)'
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
angleGraph:
    options:
        hideTitle: true
        legend:
            display: false
        axes:
            x:
                labelString: ''
                hidden: false
                maxTicksLimit: 20
                stepSize: 1
            y:
                min: -600
                max: 600
                stepSize: 10
                labelString: ''
    properties:
        lines:
            real:
                color: 'rgba(0, 106, 255, 1)' # blue
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: ture
            now:
                color: 'rgba(219, 26, 244, 1)'
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true
angleDenseGraph:
    options:
        hideTitle: true
        legend:
            display: false
        axes:
            x:
                labelString: ''
                hidden: false
                maxTicksLimit: 20
                stepSize: 1
            y:
                min: -20
                max: 20
                stepSize: 5
                labelString: ''
    properties:
        lines:
            real:
                color: 'rgba(0, 106, 255, 1)' # blue
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: ture
            now:
                color: 'rgba(219, 26, 244, 1)'
                borderWidth: 2
                pointRadius: 0
                fill: false
                showLine: true